# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ifasApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks! $(SRCROOT)/../node_modules/react-native-youtube

  # Pods for ifasApp

  # Required by RNFirebase
	pod 'Firebase/Core', '~> 5.9.0'
    pod 'Firebase/Messaging', '~> 5.9.0'
    pod 'GoogleAppMeasurement', '~> 5.2.0'
    pod 'Fabric', '~> 1.7.11'
    pod 'Crashlytics', '~> 3.10.7'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
  #’CxxBridge', # Include this for RN >= 0.47
    #’DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
   # 'RCTText',
    #’RCTNetwork',
    #$’RCTWebSocket', # Needed for debugging
    #’RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    ]
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
end
 